### ISSUE TITLE
ModuleNotFoundError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by moelius** [Infinidat/infi.clickhouse_orm#27] opened 2017-04-05 20:08 UTC
Hi, after 0.8.1 i have error in database.py: No module named 'cStringIO' with python 3.x
As i know cStringIO no longer exists in 3.x. May be you can use io.StringIO.

**Comment by M1hacka** [comment] 2017-04-06 04:53
The problem is, that it was [removed from 3.4](http://stackoverflow.com/questions/28200366/python-3-4-0-email-package-install-importerror-no-module-named-cstringio). 
This bug always occures for me (Python 3.6), and was generated by [this issue](https://github.com/Infinidat/infi.clickhouse_orm/issues/26) fix

**Comment by M1hacka** [comment] 2017-04-06 05:47
It's written [here](http://python-future.org/compatible_idioms.html#stringio), that this works in both 2 and 3 version:
```
from io import BytesIO     # for handling byte strings
from io import StringIO    # for handling unicode strings
```

**Comment by ishirav** [comment] 2017-04-06 12:15
0.8.2 was released with M1hacka's fix, so the ORM work under Python 3 again.

**Closed by ishirav** 2017-04-06 12:15 UTC
