### ISSUE TITLE
pip3 error

### ISSUE THREAD

**Issue by ainich** [Infinidat/infi.clickhouse_orm#45] opened 2017-08-18 13:47 UTC
Hello!

File "/usr/lib/python3.4/site-packages/infi/clickhouse_orm/query.py", line 193
        print self.as_sql()
                 ^
    SyntaxError: invalid syntax

**Comment by ainich** [comment] 2017-08-18 14:02
Ah, already in pull request

**Comment by M1hacka** [comment] 2017-08-21 10:59
+1 after updating to last release
0.9.4 works fine for me.

**Comment by M1hacka** [comment] 2017-08-21 11:00
I suppose the problem is print without brackets, which is not supported in python3.
It should be `print(self.as_sql())` or it shouldn't be at all (debug print =) )

**Comment by M1hacka** [comment] 2017-08-21 11:02
Found it is fixed in commit 70d34b097f4d923384566ee4319b0959b171566c by @TvoroG, waiting for release.

**Comment by ainich** [comment] 2017-08-23 11:37
No, error.

  File "/usr/lib/python3.4/site-packages/infi/clickhouse_orm/models.py", line 9, in <module>
    from .query import QuerySet
  File "/usr/lib/python3.4/site-packages/infi/clickhouse_orm/query.py", line 171, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by ishirav** [comment] 2017-08-23 11:43
@ainich this looks similar to https://github.com/sigopt/sigopt-python/issues/47
You probably need to upgrade `six`

**Comment by ainich** [comment] 2017-08-23 11:50
Ok. Its working now.

**Closed** 2017-08-23 11:50 UTC
