### ISSUE TITLE
Readonly mode broken

### ISSUE THREAD

**Issue by tswr** [Infinidat/infi.clickhouse_orm#29] opened 2017-04-24 15:21 UTC
Commit https://github.com/Infinidat/infi.clickhouse_orm/commit/5b03e660486c30222583311dabbc5b170019b5b4 breaks the simplest case of even creating a real Database object with readonly=True.

Results in `Code: 164, e.displayText() = DB::Exception: Setting 'readonly' cannot be overrided in readonly mode, e.what() = DB::Exception`

@emakarov please consider reverting.

**Comment by ishirav** [comment] 2017-04-24 15:36
Can you explain the problem? I can't reproduce it.

**Comment by tswr** [comment] 2017-04-24 16:06
I have a clickhouse instance and ro access configured. When I try to create Database object, the above mentioned exceptions occurs. When your patch is reverted, everything starts to work like a charm. Unfortunately I can't be more elaborate upon the server configuration itself.

I'm not pressuring anyone, we can live with our own fork.

**Comment by ishirav** [comment] 2017-04-24 16:14
Do you know which ClickHouse server version you're using?

**Comment by emakarov** [comment] 2017-04-24 16:23
@tswr I think I'm here not a relevant person to discuss reverting (I'm not author of this commit and also not a main maintainer. @ishirav is the author of the project)

**Comment by tswr** [comment] 2017-04-24 16:30
@emakarov sorry for misunderstanding, I saw that you merged this commit, that's why addressed you.

**Comment by ishirav** [comment] 2017-04-24 16:38
I'm using the same version and have no problem creating a readonly Database instance and running queries.

The error happens here, at line 396: https://github.com/yandex/ClickHouse/blob/e91395fa14b31ac5ee81968a1b7e97c193f274d4/dbms/src/Server/HTTPHandler.cpp

If I understand the code correctly, when the connection is already in readonly mode, the client rejects attempts to set the readonly flag.
Perhaps you are connecting with a readonly user, or have some settings in your configuratoin that force the database into readonly mode? This might explain the behavior.

**Comment by tswr** [comment] 2017-04-24 20:25
Yes, you are absolutely right, my user is readonly.

**Comment by ishirav** [comment] 2017-04-25 05:14
OK, I'll look for a workaround

**Comment by tswr** [comment] 2017-04-25 11:01
Thank you.

**Comment by ishirav** [comment] 2017-05-11 02:54
Version 0.9.0 was released with a fix.

**Closed by ishirav** 2017-05-11 02:54 UTC
